version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8000
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - 5432:5432
